### ISSUE TITLE
kernel on diet missing module

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/linux-tkg#1122]
### Same-issue check

Yes

### Linux Distribution

Archlinux

### Kernel version

6.15.2

### What happened?

I was testing the pre-build kernel-on-diet from linux-tkg on my laptop and found that the e1000e modul is missing. This prevents LAN from working. WLAN is working fine.

The laptop is a Lenovo ThinkPad X1 Carbon 6th. 
```
Network:
  Device-1: Intel Ethernet I219-V driver: e1000e
  IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: <filter>
  Device-2: Intel Wireless 8265 / 8275 driver: iwlwifi
  IF: wlan0 state: up mac: <filter>
```

### Relevant logs

No log

### My Favorite type(s) of frog

Frog
